### ISSUE TITLE
Pytest Failing "where 1 = <Result TypeError("object of type 'int' has no len()")>.exit_code"

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#17]
with updates where we pass an int as ID instead of a string, test_success_download, test_fail_download, and test_metadata are failing because  
```
assert 1 == 0
+  where 1 = <Result TypeError("object of type 'int' has no len()")>.exit_code
```
I'm really confused about where this is coming from since the only place i use len() is on a list. Any advice on how to look more into the mocks in order to see where this could be coming from? 

When I add print statements they don't show up in pytest

**Comment by PeterSulcs** [comment]
`pytest -s` turns off capturing of stdout (i.e. the print statements).

**Comment by PeterSulcs** [comment]
@cbarnes7 
Wow, that was frustrating to debug! The issue is that the invoke function always expects a list of strings, even when you would be passing numbers at the command line. Should be good to go if you make that change. I also did a code review on your PR: https://github.com/PHM-Data-Hub/lib/pull/15

**Comment by PeterSulcs** [comment]
The typer docs mention this, but their example never passes a number, so it was ambiguous: https://typer.tiangolo.com/tutorial/testing/#call-the-app

**Comment by PeterSulcs** [comment]
The type annotations confirm: https://github.com/tiangolo/typer/blob/master/typer/testing.py#L13

`args: Optional[Union[str, Iterable[str]]] = None,`

**Comment by cbarnes7** [comment]
@PeterSulcs so we can't pass an int as an argument? I'm confused

**Comment by PeterSulcs** [comment]
You can, it is just the mechanics of how the command line tool passes arguments. Everything passed in is a string.

The way the testing framework works, in order to emulate

`mdh download 1 1` 

you would pass

 `["download", "1", "1"]`

The error message was from typer trying to call `len()` on each argument expecting them to be strings as first step in passing the args to your code.

**Comment by PeterSulcs** [comment]
https://realpython.com/python-command-line-arguments/

**Comment by PeterSulcs** [comment]
Typer does conversion to an Int behind the scenes but the input from terminal is actually a string even for integer arguments
